"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class vlm_dog(object):

    __slots__ = ["mode", "velocity_x", "velocity_y", "omega_z"]

    __typenames__ = ["int64_t", "float", "float", "float"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.mode = 0
        """ LCM Type: int64_t """
        self.velocity_x = 0.0
        """ LCM Type: float """
        self.velocity_y = 0.0
        """ LCM Type: float """
        self.omega_z = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(vlm_dog._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfff", self.mode, self.velocity_x, self.velocity_y, self.omega_z))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vlm_dog._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vlm_dog._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = vlm_dog()
        self.mode, self.velocity_x, self.velocity_y, self.omega_z = struct.unpack(">qfff", buf.read(20))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if vlm_dog in parents: return 0
        tmphash = (0x8f2fffe17eeca0e3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if vlm_dog._packed_fingerprint is None:
            vlm_dog._packed_fingerprint = struct.pack(">Q", vlm_dog._get_hash_recursive([]))
        return vlm_dog._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vlm_dog._get_packed_fingerprint())[0]

